/**********************************************************************************************************************
 * \file Input_Handler.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include <stdint.h>
#include "Ifx_Types.h"

#define LOOKS_LIKE_NOISE 20U //delta값 판별하는 함수에서 이것보다 낮은 수는 noise로 판별해서 delta값에 반영 x

static uint8 cal_delta(uint8 cur, uint8 prev)
{
    return ((cur > prev) ? (cur - prev) : (prev - cur));
}

// 센서 값의 변화량, warning, critical 임계값 입력 시 해당 delta값이 어느 safe_state에 해당하는지 판별
static DeltaLevel classify_delta(uint8 delta, uint8 warn, uint8 critical)
{
    if (delta >= critical)
    {
        return DELTA_CRITICAL;
    }
    else if (delta >= warn && delta < critical)
    {
        return DELTA_WARNING;
    }
    else
    {
        return DELTA_NORMAL;
    }
}

// 하나의 센서에 대한 data를 update
static void update_sensor_data(SensorState *sensor, uint8 new_data, uint8 warn, uint8 critical)
{
    // 일단은 구조체에 넣어서 그 전값만 비교해서 delta값 판별
    // 5번 이전에 들어온 data랑도 비교하는 방식 추가하면 좋을 수도? 쓸모가 있을진 모르겠음
    sensor->prev = sensor->cur;
    sensor->cur = new_data;
    sensor->delta = cal_delta(sensor->cur, sensor->prev);

    // delta값이 미세하게 변하는 경우 noise로 판단
    if (sensor->delta < LOOKS_LIKE_NOISE)
    {
        sensor->delta = 0U;
    }
    sensor->deltalevel = classify_delta(sensor->delta, warn, critical);
}

//can으로 받아온 데이터 구조체에 초기화
void input_handler_init(VehicleState *state, const InputData *data)
{
    //init button
    state->button = data->button;

    //init brake
    state->brake.prev = data->brake_value;
    state->brake.cur = data->brake_value;
    state->brake.delta = 0U;
    state->brake.deltalevel = DELTA_NORMAL;

    //init accel
    state->accel.prev = data->accel_value;
    state->accel.cur = data->accel_value;
    state->accel.delta = 0U;
    state->accel.deltalevel = DELTA_NORMAL;

    //init steering
    state->steer.prev = data->steer_value;
    state->steer.cur = data->steer_value;
    state->steer.delta = 0U;
    state->steer.deltalevel = DELTA_NORMAL;

    //init system state
    state->systemstate = SYS_STATE_NORMAL;
    state->logcode = LOG_NONE;
}

//새 데이터를 받아서 내부 상태를 갱신
void input_handler_update(VehicleState *state, const InputData *data)
{
    state->button = data->button;
    update_sensor_data(&state->brake, data->brake_value, 100U, 180U);
    update_sensor_data(&state->accel, data->accel_value, 80U, 150U);
    update_sensor_data(&state->steer, data->steer_value, 120U, 220U);
}

