/**********************************************************************************************************************
 * \file State_Manager.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#include "State_Manager.h"

// 전체 센서의 상태를 받아온 뒤 최종 시스템 상태를 결정
void classify_state(VehicleState *state)
{
    state->systemstate = SYS_STATE_NORMAL;
    state->logcode = LOG_NONE;

    if ((state->brake.deltalevel == DELTA_CRITICAL) ||
        (state->accel.deltalevel == DELTA_CRITICAL) ||
        (state->steer.deltalevel == DELTA_CRITICAL))
    {
        state->systemstate = SYS_STATE_CRITICAL;
        // 로그 기록
        if (state->brake.deltalevel == DELTA_CRITICAL)
        {
            state->logcode = LOG_BRAKE_CRITICAL;
        }
        else if (state->accel.deltalevel == DELTA_CRITICAL)
        {
            state->logcode = LOG_ACCEL_CRITICAL;
        }
        else
        {
            state->logcode = LOG_STEER_CRITICAL;
        }
        return;
    }

    if ((state->brake.deltalevel == DELTA_WARNING) ||
        (state->accel.deltalevel == DELTA_WARNING) ||
        (state->steer.deltalevel == DELTA_WARNING))
    {
        state->systemstate = SYS_STATE_WARNING;

        // 로그 기록
        if (state->brake.deltalevel == DELTA_WARNING)
        {
            state->logcode = LOG_BRAKE_WARNING;
        }
        else if (state->accel.deltalevel == DELTA_WARNING)
        {
            state->logcode = LOG_ACCEL_WARNING;
        }
        else
        {
            state->logcode = LOG_STEER_WARNING;
        }
        return;
    }
}
