/**********************************************************************************************************************
 * \file Types.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#ifndef TYPES_H
#define TYPES_H

#include <stdint.h>

typedef enum{
    SYS_STATE_NORMAL = 0,
    SYS_STATE_WARNING,
    SYS_STATE_CRITICAL,
    SYS_STATE_FATAL_NO_RESPONSE
}SystemState; // 전체 시스템 상태

typedef enum{
    DELTA_NORMAL = 0,
    DELTA_WARNING,
    DELTA_CRITICAL
}DeltaLevel; // 변화량 상태

typedef enum{
    LOG_NONE = 0,
    LOG_ACCEL_WARNING,
    LOG_ACCEL_CRITICAL,
    LOG_BRAKE_WARNING,
    LOG_BRAKE_CRITICAL,
    LOG_STEER_WARNING,
    LOG_STEER_CRITICAL,
    LOG_TIMEOUT
}LogCode; // 어떤 이유로 상태가 변했는지

typedef struct{
        uint8       button;
        uint8       brake_value;
        uint8       accel_value;
        uint8       steer_value;
}InputData; // CAN으로 받아온 프레임을 parsing해서 담아 둘 곳

typedef struct{
        uint8       prev;
        uint8       cur;
        uint8       delta;
        DeltaLevel deltalevel;
}SensorState; // 하나의 센서에 대한 상태 저장 구조체

typedef struct{
        SensorState brake;
        SensorState accel;
        SensorState steer;

        uint8       button;

        SystemState systemstate;
        LogCode     logcode;
}VehicleState; // 차량의 상태에 대한 구조체
#endif
